export const strings = {
  titleDate: "7/10",
  title: "מתקבלים דיווחים על היערכות לפלישה. אתה צריך ללחוץ עליהם כדי להעביר אותם לביבי כדי שיציל אותנו",
  start: "התחל",
  hudWake: "WAKE HIM UP",
  miss: "פספסת.",
  stir: "עוד קצת...",
  tooMuch: "יותר מדי דברים בבת אחת.",
  commandReceived: "פקודה התקבלה.",
  stay: "הישאר בעמדה",
  leave: "צא מיד",
  freeze1: "נכשלת במשימתך להעיר את ביבי ולהציל אלפי אנשים",
  freeze2: "נכשלת? בגדת?",
  calmVoice: "ואולי ...",
  twistObject: "אולי הבעיה היתה בכלל בזה שאמור להתעורר",
  twistResult: "זה לא היה בידיים שלך.",
  endingAsk: "כמה דברים הצלחת לתפוס?",
  notTheTest: "זה לא המבחן.",
  theTest: "המבחן הוא ללמוד מטעויות ולא לבחור אדם כושל.",
  playAgain: "שוב",
  quoteSourceFallback: "מקור",
  quoteDateFallback: "תאריך",
  genericQuote: [
    { text: "הודעה ממתינה.", source: "מערכת · תאריך" },
    { text: "דיווח התקבל.", source: "מערכת · תאריך" },
    { text: "עדכון סטטוס.", source: "מערכת · תאריך" },
    { text: "פקודה בתור.", source: "מערכת · תאריך" },
  ],
  stub: {
    play: "משחק",
    freeze: "הקפאה",
    twist: "טוויסט",
    ending: "סיום",
  },
} as const;
